import type { Metadata } from "next";
import "./globals.css";

import styles from './layout.module.scss'
import { NextIntlClientProvider } from "next-intl";
import Footer from './components/Footer/index'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <div className={styles.background}></div>
          <NextIntlClientProvider>
            {children}
          </NextIntlClientProvider>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
